# Quick start

Although this section might not be the latest version, the general idea won't
change. Please see 
[R bookdownplus Textbook](https://bookdown.org/baydap/bookdownplus) to keep up 
with the update.

## Preparation

Before starting, you have to install R, RStudio, bookdown package, and
other software and packages (i.e. Pandoc, LaTeX, rmarkdown, rticle,
knitr, etc.) which bookdown depends on. See the official 
[manual](https://bookdown.org/yihui/bookdown/) of bookdown for details. 
Additionally, if you want to produce a poster, phython must be installed before 
using, and the path of phython might have to be added to the environmental 
variables for Windows users.

## Installation

```
install.package("bookdownplus")
# or
devtools::
  install_github("pzhaonet/bookdownplus")
```

## Generate demo files

Run the following codes, and you will get some files (e.g. `index.Rmd`, 
`body.Rmd`, `bookdownplus.Rproj`) and folders in your working directory.

```
getwd() # this is your working directory. run setwd() to change it.
bookdownplus::bookdownplus()
```

## Build a demo book

Now open `bookdownplus.Rproj` with RStudio, and press `ctrl+shift+b` to compile
it. Your will get a book file named `*.pdf` in `_book/`folder.

## Write your own

Write your own text in `index.Rmd` and `body.Rmd`, and build your own lovely 
book.

## More outputs

By default, the book is in a pdf file. From 'bookdownplus' 1.0.3, users can get
more output formats, including 'word', 'html' and 'epub'. Run:

```
bookdownplus::
  bookdownplus(template = 'article',
               more_output = c('html', 'word', 'epub'))
```

## Recommendations

I have been developing some other packages, which bring more features into 
'bookdown', such as:

- mindr [@R-mindr], which can extract the outline of your book and turn it into
  a mind map, and

- pinyin [@R-pinyin], which can automatically generate ['{#ID}'](https://bookdown.org/yihui/bookdown/cross-references.html) of the 
  chapter headers even if there are Chinese characters in them.

Both of them have been released on CRAN and can be installed via:

```
install.packages('mindr')
install.packages('pinyin')
```

Enjoy your bookdowning!

## Models

Eq. \@ref(eq:mc2) is an equation.

\begin{equation}
E = mc^2
  (\#eq:mc2)
\end{equation}

It can be written as $E = mc^2$.
